site_name: TPMS Installation Manual
site_author: Neosens


theme:
  name: material
  pdf: true
  logo: images/nlp_icon.png
  favicon: images/nlp_icon.png
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: lightblue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: lightblue
markdown_extensions:
  - attr_list
  - admonition

extra_css:
- styles/extra.css

plugins:
  - search

nav:
  - Home: index.md
  - Receiver: receiver/receiver.md
      - Specification: receiver/receiver_spec.md
      - Enclosure and Cables: receiver/receiver_enclosure.md
      - Installation: receiver/receiver_installation.md
      - Configuration and Diagnostics: receiver/receiver_configuration.md
      - Certificates: receiver/receiver_certificates.md
  - External Sensors: sensors/external.md
  - Internal Sensors: sensors/internal.md
  - Display: display/display.md
      - Specification: display/display_spec.md
      - Enclosure and Cables: display/display_buttons.md