site_name: TPMS Installation Manual
site_author: Neosens


theme:
  name: material
  pdf: true
  logo: images/nlp_icon.png
  favicon: images/nlp_icon.png
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: lightblue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: lightblue
markdown_extensions:
  - attr_list
  - admonition

extra_css:
- styles/extra.css

plugins:
  - search
  # - exporter:
  #     formats:
  #       pdf:
  #         enabled: true
  #         stylesheets:
  #           - resources/stylesheets/pdf.scss
  #         covers:
  #           front: resources/templates/covers/front.html.j2
  #         aggregator:
  #           enabled: true
  #           output: NLP_Installation_Manual.pdf
  #           covers: limits

nav:
  - Home: index.md
  - Receiver: 
      - Specification: receiver/receiver_spec.md
      - Enclosure and Cables: receiver/receiver_enclosure.md
      - Installation: receiver/receiver_installation.md
      - Configuration and Diagnostics: receiver/receiver_configuration.md
      - Certificates: receiver/receiver_certificates.md
  - External Sensors: 
      - Specification: sensors/external_spec.md
      - Sensor Types and Accessories: sensors/external_types_installation.md
      - Installation Tool Kit: sensors/installation_tool_kit.md
  - Internal Sensors: 
      - Specification: sensors/internal_spec.md
      - Valve-mounted Sensor: sensors/internal_valve.md
      - Strap-mounted Sensor: sensors/internal_strap.md
  - Display: 
      - Specification: display/display_spec.md
      - Buttons Functionality: display/display_buttons.md