site_name: Installation Manual v1.0
site_author: Neosens


theme:
  name: material
  pdf: true
  logo: images/tiresens_bw.png
  favicon: images/tiresens_sq.png
  features:
    - navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  
  palette:
    - scheme: default
      primary: custom
      accent: black 
markdown_extensions:
  - attr_list
  - admonition

extra_css:
- styles/extra.css

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - privacy
  - search
  - encryptcontent:
        title_prefix: ''
        summary: 'This content is password protected.'
        password_file: 'passwords.yml'
  # - exporter:
  #     formats:
  #       pdf:
  #         enabled: true
  #         stylesheets:
  #           - resources/stylesheets/pdf.scss
  #         covers:
  #           front: resources/templates/covers/front.html.j2
  #         aggregator:
  #           enabled: true
  #           output: Tiresens_Installation_Manual_v1-0.pdf
  #           covers: limits

nav:
  - Home: index.md
  - Receiver: 
      - Specification: receiver/receiver_spec.md
      - Enclosure and Cables: receiver/receiver_enclosure.md
      - Installation: receiver/receiver_installation.md
      - Configuration and Diagnostics: receiver/receiver_configuration.md
      - Certificates: receiver/receiver_certificates.md
  - External Sensors: 
      - Specification: sensors/external_spec.md
      - Sensor Types and Accessories: sensors/external_types_installation.md
      - Installation Tool Kit: sensors/installation_tool_kit.md
  - Internal Sensors: 
      - Specification: sensors/internal_spec.md
      - Valve-mounted Sensor: sensors/internal_valve.md
      - Strap-mounted Sensor: sensors/internal_strap.md
  - Display: 
      - Specification: display/display_spec.md
      - Buttons Functionality: display/display_buttons.md